name: wallpapers_hd
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+10

environment:
  sdk: ">=3.0.0 <4.0.3"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  # New Dependencies
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.8
  share_plus: ^9.0.0
  path_provider: ^2.1.3
  connectivity_plus: ^6.0.3
  fluttertoast: ^8.2.6
  flutter_wallpaper_manager: ^0.0.4
  cached_network_image: ^3.3.1
  sqflite: ^2.3.3+1
  shimmer: ^3.0.0
  firebase_auth: ^5.1.0
  permission_handler: ^11.3.1
  purchases_flutter: ^6.29.0
  google_sign_in: ^6.2.1
  onesignal_flutter: ^5.2.0
  firebase_messaging: ^15.0.1
  flutter_local_notifications: ^17.1.2

  flutter_html: any

  lottie: ^3.1.2
  gallery_saver: ^2.3.2
  image_picker: ^1.1.2

  url_launcher: ^6.3.0
  palette_generator: ^0.3.3+3
  flutter_staggered_grid_view: ^0.7.0
  animated_bottom_navigation_bar: ^1.3.3
  app_settings: ^5.1.1
  firebase_analytics: ^11.0.1
  firebase_crashlytics: ^4.0.1
  flutter_rating_bar: ^4.0.1

  flutter_cache_manager: ^3.3.2
  firebase_core: ^3.1.0
  path: ^1.9.0
  facebook_app_events: ^0.19.2

  flutter_device_id: ^1.0.1
  app_tracking_transparency: ^2.0.5
  sign_in_with_apple: ^6.1.0
  easy_ads_flutter: ^2.4.4


  http: any
dependency_overrides:
  http: ^1.2.1
  easy_audience_network:
    git:
      url: https://github.com/kaushikgodhani/audience_network_flutter.git
      ref: c67f254ea8d3006024daecd26776ad55522eaf05

dev_dependencies:
  flutter_test:
    sdk: flutter

  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/mainicon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/Lottie/

  fonts:
    - family: M
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: SB
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: R
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
