// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbA_VdDLHZMeudzhHqSH7Xp5wtV6yqCko',
    appId: '1:548518483337:android:6e723d9d6a7fdaafe73d58',
    messagingSenderId: '548518483337',
    projectId: 'cc-wallpaper-78643',
    storageBucket: 'cc-wallpaper-78643.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-pMq51uIRtoeEllTGgMHmiwcMQWT4buA',
    appId: '1:548518483337:ios:b39bf84a2c48720fe73d58',
    messagingSenderId: '548518483337',
    projectId: 'cc-wallpaper-78643',
    storageBucket: 'cc-wallpaper-78643.appspot.com',
    androidClientId: '548518483337-g026g8bno2btl7hmju88qrrjg6su0lom.apps.googleusercontent.com',
    iosClientId: '548518483337-1huo4opdl8pu5ct2n7gv2vltfsp0asvo.apps.googleusercontent.com',
    iosBundleId: 'com.vocsy.wallpapersHd',
  );
}
