/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class Res {
  static const String arrow_back = "assets/icons/arrow_back.svg";
  static const String edit = "assets/icons/edit.svg";
  static const String google = "assets/images/google.svg";
  static const String image_not_found = "assets/images/image-not-found.png";
  static const String info = "assets/icons/info.svg";
  static const String mainicon = "assets/images/mainicon.png";
  static const String policy = "assets/icons/policy.svg";
  static const String Poppins_Medium = "assets/fonts/Poppins-Medium.ttf";
  static const String Poppins_Regular = "assets/fonts/Poppins-Regular.ttf";
  static const String Poppins_SemiBold = "assets/fonts/Poppins-SemiBold.ttf";
  static const String share = "assets/icons/share.svg";
  static const String star = "assets/icons/star.svg";
  static const String apple = "assets/icons/apple.svg";
  static const String logout = "assets/icons/logout_3.svg";
  static const String delete = "assets/icons/delete_1.svg";
  static const String premium = "assets/icons/premium.svg";
  static const String terms = "assets/icons/terms.svg";
}
